version: "3.3"
services:
  borregrado-telegram-bot:
    image: swr.la-north-2.myhuaweicloud.com/eduardo/borregrado-telegram-bot:latest
    container_name: borregrado-telegram-bot
    env_file:
      - .env
    restart: unless-stopped
