FROM python:3.9

# Install system dependencies
RUN apt-get update && apt-get install -y mariadb-client dnsutils

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code
COPY . .

USER daemon

# Run the Telegram bot
CMD ["python", "app.py"]
